services:
  - type: web
    name: resumeiq-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm && python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('punkt_tab')"
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: ResumeIQ
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false
